name: Destroy Infrastructure

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: terraform

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_access_token: ${{ secrets.ACCESS_TOKEN }}

jobs:
  tf_destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Retrieve Repository URL for Amplify
      run: |
        echo "TF_VAR_repository=https://github.com/${{ github.repository }}" >> $GITHUB_ENV

    - name: Initialize Terraform
      run: terraform init

    - name: Terraform Destroy
      run: terraform destroy -auto-approve