apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.application_name | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    github.com/project-slug: ${{values.projectSlug}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}
  dependsOn:
    - component:default/demo-component
    - resouce:demo-db
  providesApis:
    - demo-provided-apis
  consumesApis:
    - demo-consumed-apis